server:
  port: 5000
  servlet:
    encoding:
      charset: utf-8
      force: true

sentry:
  enable-tracing: true
  send-default-pii: true # 사용자 정보 기록
  environment: development # 개발환경 / environment=production
  logging: # 범위
    minimum-event-level: "WARN"
    minimum-breadcrumb-level: "INFO"
  dsn: ${sentry.dsn}
  sample-rate: 0.5 # 샘플링 비율 1=100% 다 보냄
  #traces-sample-rate # 트랜잭션 비율 설정

cloud:
  aws:
    region:
      static: ap-northeast-2
      auto: false
    s3:
      bucket: villages-3
    credentials:
      access-key: ${s3.access.key}
      secret-key: ${s3.secret.key}
    stack:
      auto: false

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  datasource:
    url: jdbc:mariadb://${rds.hostname}:${rds.port}/${rds.db.name}?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${rds.username}
    password: ${rds.password}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB53Dialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true

logging:
  level:
    # 로그레벨 설정 DEBUG로 개발하고 INFO로 배포한다.
    '[shop.mtcoding.securityapp]': INFO # DEBUG 레벨부터 에러 확인할 수 있게 설정하기
    '[org.hibernate.type]': TRACE # 콘솔 쿼리에 ? 에 주입된 값 보기

meta:
  name: ${hs512.secret}
    